
<div class="tri-double-col team-info">

    <h3 class="team-name">Benjamin Arnold</h3>

    <span class="team-title">Lead Developer</span> Ben is the brain power
	of the team, he has developed all the code that powers the game and is
	incredibly focussed on keeping his work as optimised as possible. All
	ideas generated by the designers and community are currently
	implemented via Ben's fingers!
</div>

<div class="tri-col-3 empty">

	<a href="/Assets/images/ProfileImages/BenA.png" data-lightbox="images"
		title="Benjamin Arnold" class="large image"><img
		src="/Assets/images/ProfileImages/BenA_thumb_250x200.png"
		class="large image" /></a>

</div>

<div class="tri-col-1 empty">

	<a href="/Assets/images/ProfileImages/AnthonyK.jpg"
		data-lightbox="images" title="Anthony Keeton" class="large image"><img
		src="/Assets/images/ProfileImages/AnthonyK_thumb_250x200.jpg"
		class="large image" /></a>

</div>

<div class="tri-double-col right team-info">

	<h3 class="team-name">Anthony Keeton</h3>

	<span class="team-title">Lead Designer</span> Anthony AKA Damion Rayne, 
	previously of military occupation, has worked as Community Manager of 
	Kerbal Space Program, and has recenlty worked on Legends of Aetherius. 
	He has now accepted a role as designer for Seed of Andromeda alongside 
	Ben and Sebastian.

</div>

<div class="tri-double-col team-info">

	<h3 class="team-name">Sebastian Corfitzen</h3>

	<span class="team-title">Designer</span> Sebastian worked his way on to 
	the team through bombarding Ben with great ideas, having previously 
	worked on some of his own game projects he now works on the design of 
	Seed of Andromeda. Sebastian is multi-talented and spends time on voxel 
	models, tree generation, and general Design. He also spends a good 
	amount of time eating pizza and playing about in PhotoShop. 
</div>

<div class="tri-col-3 empty">

	<a href="/Assets/images/ProfileImages/SebastianC.png"
		data-lightbox="images" title="Sebastian Corfitzen" class="large image"><img
		src="/Assets/images/ProfileImages/SebastianC_thumb_250x200.png"
		class="large image" /></a>

</div>

<!-- Leave in for now, just commented out, he may return!

<div class="tri-col-1 empty">

	<a href="/Assets/images/ProfileImages/Scuttles.jpg"
		data-lightbox="images" title="Scuttles" class="large image"><img
		src="/Assets/images/ProfileImages/Scuttles_thumb_250x200.jpg"
		class="large image" /></a>

</div>

<div class="tri-double-col right team-info">

	<h3 class="team-name">Scuttles</h3>

	<span class="team-title">Graphics Artist</span> Scuttes, creator of LB
	Photorealism for Minecraft, is now a graphics artist for Seed of
	Andromeda, working on the default texture packs, as well as general
	images relating to Seed of Andromeda such as its logo.

</div>

-->

<div class="tri-col-1 empty">

	<a href="/Assets/images/ProfileImages/JoshA.jpg" data-lightbox="images"
		title="Joshua Arnold" class="large image"><img
		src="/Assets/images/ProfileImages/JoshA_thumb_250x200.jpg"
		class="large image" /></a>

</div>

<div class="tri-double-col right team-info">

	<h3 class="team-name">Joshua Arnold</h3>

	<span class="team-title">Sound Artist</span> Josh is the creative 
	genius behind all of Seed of Andromeda's music and sound, he has 
	produced many high quality soundtracks of his own previously, and 
	has now turned his talent towards producing all manner of music 
	and sounds for your ears to enjoy!

</div>

<div class="tri-double-col team-info">

	<h3 class="team-name">Matthew Marshall</h3>

	<span class="team-title">Web Developer / Designer</span> Matthew is the
	creative force behind the Seed of Andromeda website, and he also
	assists in the design of the game. Between sessions working on the
	website's design he works on Reddit posts that have more text than a
	novel as well as having occasional cracks at developing systems for the
	website. Matthew is one of the more active devs on the forum and is
	always willing to offer his perspective on an idea!
</div>

<div class="tri-col-3 empty">

	<a href="/Assets/images/ProfileImages/MatthewM.jpg"
		data-lightbox="images" title="Matthew Marshall" class="large image"><img
		src="/Assets/images/ProfileImages/MatthewM_thumb_250x200.jpg"
		class="large image" /></a>

</div>

<div class="tri-col-1 empty">

	<a href="/Assets/images/ProfileImages/GeorgH.png"
		data-lightbox="images" title="Georg Hammerschmid" class="large image"><img
		src="/Assets/images/ProfileImages/GeorgH_thumb_250x200.png"
		class="large image" /></a>

</div>

<div class="tri-double-col right team-info">

	<h3 class="team-name">Georg Hammerschmid</h3>

	<span class="team-title">Graphics Artist</span> Georg is a talented
	graphics artist and scientist! He started out by creating texture mods
	for SoA and was noticed for his skill and style! He is currently
	Studying Technical Chemistry in Austria, but enjoys making
	photorealistic textures in his spare time. No doubt his scientific
	background will aid SoA development! Forum name: _zombiehunter.

</div>

<div class="tri-double-col team-info">

	<h3 class="team-name">Andreas Ressl</h3>

	<span class="team-title">3D Artist</span> Andreas is an incredibly
	talented hobby artist! He currently works in construction in Austria,
	and has studied graphic design. His incredible voxel modeling skills
	grabbed the attention of the SoA team thanks to his contributions on
	the forum! As SoA develops further, Andreas will be designing the 3D
	models and textures. He will also be helping design the voxel damage
	and animation systems! Forum name: Gilzokha
</div>

<div class="tri-col-3 empty">

	<a href="/Assets/images/ProfileImages/AndreasR.jpg"
		data-lightbox="images" title="Andreas Ressl" class="large image"><img
		src="/Assets/images/ProfileImages/AndreasR_thumb_250x200.jpg"
		class="large image" /></a>

</div>

<div class="tri-col-1 empty">

	<a href="/Assets/images/ProfileImages/Jesses_dog.jpg" data-lightbox="images"
		title="Jesse's dog as a placeholder" class="large image"><img
		src="/Assets/images/ProfileImages/Jesses_dog_thumb_250x200.jpg"
		class="large image" /></a>
</div>

<div class="tri-double-col right team-info">

	<h3 class="team-name">Jesse Leskinen</h3>

	<span class="team-title">Web Developer</span> Jesse is an incredibly
	talented web developer, and is working on the backend of the website,
	as well as integration between the game and the mod respository used by
	the forums. His work will help make the site become a much more smooth
	experience and bring a unique way of tackling the challenges of such a
	project as this.
</div>

<div class="tri-double-col team-info">

    <h3 class="team-name">Patrick Cavanagh</h3>

	<span class="team-title">Community Manager</span> Patrick is our first 
	community manager, he runs most - no doubt, soon, all - of our social media groups 
	and is also the youngest of the team! He is known for his ability for eloquence and 
	for understanding the wants and needs of the community with ease. He rules with a 
	feathery fist of iron, so be warned - don't antagonise him, or a soft tickle may turn deadly.
</div>

<div class="tri-col-3 empty">

	<a href="/Assets/images/ProfileImages/PatrickC.jpg"
		data-lightbox="images" title="Patrick Cavanagh" class="large image"><img
		src="/Assets/images/ProfileImages/PatrickC_thumb_250x200.jpg"
		class="large image" /></a>

</div>

<div class="tri-col-1 empty">

    <a href="/Assets/images/ProfileImages/NathanM.jpg"
		data-lightbox="images" title="Nathan Matthews" class="large image"><img
		src="/Assets/images/ProfileImages/NathanM_thumb_250x200.jpg"
		class="large image" /></a>

</div>

<div class="tri-double-col right team-info">

	<h3 class="team-name">Nathan Matthews</h3>

	<span class="team-title">Programmer</span> Nathan has been a friend and classmate of Ben at the University Of Tennessee at Knoxville. They 
    have taken several classes together, and during this time Ben noticed his exceptional ability and 
    drive. Nathan has a knack for OpenGL and C++ and enjoys working on games in his spare time. He is 
    also experienced, having worked as an intern at ORNL in Oakridge Tennessee. Nathan will be a valuable 
    asset to the team, starting by helping to develop a custom voxel editor!

</div>

<div class="tri-double-col team-info">

	<h3 class="team-name">Cristian Zaloj</h3>

	<span class="team-title">Programmer</span> Cristian is a Romanian vampire ninja pirate currently studying
    at Cornell. He has a good background in game development, and he has
    even made a voxel RTS! Cristian knows quite a few programming languages,
    and is going to surely be a great programmer on the team!

</div>

<div class="tri-col-3 empty">

    <a href="/Assets/images/ProfileImages/CristianZ.png"
		data-lightbox="images" title="Cristian Zaloj" class="large image"><img
		src="/Assets/images/ProfileImages/CristianZ_thumb_250x200.png"
		class="large image" /></a>

</div>

<div class="tri-col-1 empty">

    <a href="/Assets/images/ProfileImages/BrianB.jpg"
		data-lightbox="images" title="Brian Bruggeman" class="large image"><img
		src="/Assets/images/ProfileImages/BrianB_thumb_250x200.jpg"
		class="large image" /></a>

</div>

<div class="tri-double-col right team-info">

	<h3 class="team-name">Brian Bruggeman</h3>

	<span class="team-title">Software Engineering Consultant</span> Brian is a seasoned software
    engineer who has many years of programming experience. He has worked on
    software for planes, trains, automobiles, biometric hand scanners, big data,
    and more! Brian is quite a busy guy, but he has kindly offered his assistance
    to the SoA team. Brian will help with systems programming, and will provide
    the other devs with helpful software engineering advice. Brian's experience
    will surely help us all grow as a team!

</div>

<div class="tri-double-col team-info">

	<h3 class="team-name">Jeremy Fischer</h3>

    <span class="team-title">Intern Programmer</span> Jeremy is an extremely intelligent and technically minded
    person. He has experience with network programming and server management, and
    he is going to host the first dedicated SoA team server when multiplayer is
    implemented! Jeremy's dedication and talent ensure that he will grow into
    a very skilled game programmer!
</div>

<div class="tri-col-3 empty">

    <a href="/Assets/images/ProfileImages/JeremyF.jpg"
    	data-lightbox="images" title="Jeremy Fischer" class="large image"><img
		src="/Assets/images/ProfileImages/JeremyF_thumb_250x200.jpg"
		class="large image" /></a>
</div>

<div class="tri-col-1 empty">

    <a href="/Assets/images/ProfileImages/FrankF.jpg"
		data-lightbox="images" title="Frank McCoy" class="large image"><img
		src="/Assets/images/ProfileImages/FrankF_thumb_250x200.jpg"
		class="large image" /></a>

</div>

<div class="tri-double-col right team-info">

    <h3 class="team-name">Frank McCoy</h3>

	<span class="team-title">Programmer</span> Frank is a talented programmer 
    who has been working on his own game engine in Java! He is the lead programmer for 
    the robotics team associated with his high school, and he even teaches other students 
    how to program! He has experience with a wide range of programming languages and
    APIs, and he since he is a fast learner he will likely make great progress
    on the SoA team!

</div>