
<div class="tri-double-col team-info">

	<h3 class="team-name">Benjamin Arnold</h3>

	<span class="team-title">Lead Developer</span> Ben is the brain power
	of the team, he has developed all the code that powers the game and is
	incredibly focussed on keeping his work as optimised as possible. All
	ideas generated by the designers and community are currently
	implemented via Ben's fingers!

</div>

<div class="tri-col-3 empty">

	<img src="Assets/images/ProfileImages/BenA.png" class="large image" />

</div>

<div class="tri-col-1 empty">

	<img src="Assets/images/ProfileImages/AnthonyK.jpg" class="large image" />

</div>

<div class="tri-double-col right team-info">

	<h3 class="team-name">Anthony Keeton</h3>

	<span class="team-title">Designer</span> Anthony AKA Damion Rayne,
	previously of military occupation, has worked as Community Manager of
	Kerbal Space Program, and has recenlty worked on Legends of Aetherius.

	He has now accepted a role as designer for Seed of Andromedea alongside
	Ben and Sebastian.

</div>

<div class="tri-double-col team-info">

	<h3 class="team-name">Sebastian Corfitzen</h3>

	<span class="team-title">Designer</span> Sebastian worked his way on to
	the team through bombarding Ben with great ideas, having previously
	worked on some of his own game projects he now works on the design of

	Seed of Andromeda. Sebastian is multi-talented and spends time on voxel
	models, tree generation, and general Design. He also spends a good
	amount of time eating pizza and playing about in PhotoShop.

</div>

<div class="tri-col-3 empty">

	<img src="Assets/images/ProfileImages/SebastianC.png"
		class="large image" />

</div>

<div class="tri-col-1 empty">

	<img src="Assets/images/ProfileImages/Scuttles.jpg" class="large image" />

</div>

<div class="tri-double-col right team-info">

	<h3 class="team-name">Scuttles</h3>

	<span class="team-title">Graphics Artist</span> Scuttes, creator of LB
	Photorealism for Minecraft, is now a graphics artist for Seed of
	Andromeda, working on the default texture packs, as well as general
	images relating to Seed of Andromeda such as its logo.

</div>

<div class="tri-double-col team-info">

	<h3 class="team-name">Joshua Arnold</h3>

	<span class="team-title">Sound Artist</span> Josh is the creative
	genius behind all of Seed of Andromeda's music, currently working on
	the intro music, he has produced many high quality soundtracks of his
	own previously.

</div>

<div class="tri-col-3 empty">

	<img src="Assets/images/placeholder_4.jpg" class="large image" />

</div>

<div class="tri-col-1 empty">

	<img src="Assets/images/ProfileImages/MatthewM.jpg" class="large image" />

</div>

<div class="tri-double-col right team-info">

	<h3 class="team-name">Matthew Marshall</h3>

	<span class="team-title">Web Developer / Designer</span> Matthew is the
	creative force behind the Seed of Andromeda website, and he also
	assists in the design of the game. Between sessions working on the
	website's design he works on Reddit posts that have more text than a
	novel as well as having occasional cracks at developing systems for the
	website. Matthew is one of the more active devs on the forum and is
	always willing to offer his perspective on an idea!

</div>

<div class="tri-double-col team-info">

	<h3 class="team-name">Georg Hammerschmid</h3>

	<span class="team-title">Graphics Artist</span> Georg is a talented
	graphics artist and scientist! He started out by creating texture mods
	for SoA and was noticed for his skill and style! He is currently
	Studying Technical Chemistry in Austria, but enjoys making
	photorealistic textures in his spare time. No doubt his scientific
	background will aid SoA development! Forum name: _zombiehunter.

</div>

<div class="tri-col-3 empty">

	<img src="Assets/images/ProfileImages/GeorgH.png" class="large image" />

</div>

<div class="tri-col-1 empty">

	<img src="Assets/images/ProfileImages/AndreasR.jpg" class="large image" />

</div>

<div class="tri-double-col right team-info">

	<h3 class="team-name">Andreas Ressl</h3>

	<span class="team-title">3D Artist</span> Andreas is an incredibly
	talented hobby artist! He currently works in construction in Austria,
	and has studied graphic design. His incredible voxel modeling skills
	grabbed the attention of the SoA team thanks to his contributions on
	the forum! As SoA develops further, Andreas will be designing the 3D
	models and textures. He will also be helping design the voxel damage
	and animation systems! Forum name: Gilzokha
</div>

<div class="tri-double-col team-info">

	<h3 class="team-name">Jesse Leskinen</h3>

	<span class="team-title">Web Developer</span> Jesse is an incredibly
	talented web developer, and is working on the backend of the website,
	as well as integration between the game and the mod respository used by
	the forums. His work will help make the site become a much more smooth
	experience and bring a unique way of tackling the challenges of such a
	project as this.
</div>

<div class="tri-col-3 empty">

	<img src="Assets/images/placeholder_4.jpg" class="large image" />
</div>